<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.wolt.dopc.exception.GlobalExceptionHandlerTest$ValidationErrorsTests" tests="3" skipped="0" failures="0" errors="0" timestamp="2025-01-16T14:14:08" hostname="Resits-MacBook-Pro.local" time="0.21">
  <properties/>
  <testcase name="should handle MethodArgumentNotValidException with single field error()" classname="com.wolt.dopc.exception.GlobalExceptionHandlerTest$ValidationErrorsTests" time="0.001"/>
  <testcase name="should handle MethodArgumentNotValidException with multiple field errors()" classname="com.wolt.dopc.exception.GlobalExceptionHandlerTest$ValidationErrorsTests" time="0.001"/>
  <testcase name="should handle ConstraintViolationException()" classname="com.wolt.dopc.exception.GlobalExceptionHandlerTest$ValidationErrorsTests" time="0.208"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
